### ISSUE TITLE
Performance degradation in latest 1.8 releases

### ISSUE THREAD

**Issue by marmeladema** [rust-lang/regex#988] opened 2023-04-24 11:11 UTC
#### What version of regex are you using?

Upgrading from 1.7.1 to 1.8.1

#### Describe the bug at a high level.

Performance of parsing/building `Regex` has significantly decreased by between 10% and 50% more CPU instructions.
It was observed for regexes compiled with `regex::bytes::RegexBuilder::new(pattern).unicode(false)`.
But it might be a more general issue since this is the only way we are building regexes.

#### What are the steps to reproduce the behavior?

Build a regex using 1.8.1 version with `regex::bytes::RegexBuilder::new(pattern).unicode(false)`.
Will try to come up with a standalone reproducer but I haven't had time yet.
I know the issue is not properly actionable just yet but I figured someone else might have already encountered the issue.

#### What is the expected behavior?

Similar performance characteristics to build regexes than 1.7.x releases.

**Comment by BurntSushi** [comment] 2023-04-24 11:36
Thanks for the report! Without a real example though, I can't do anything.

I'm pretty sure we've discussed this in the past, but the number of CPU instructions isn't really what I care about. It's a useful metric and a good flag for "hey look over here." The thing I actually care about is real resource usage: memory and time.

In 1.8, there are some more optimizations being done on the `Hir`, so some regressions here are expected. But I'd have to dig into a real example to see.

In 1.9, I expect regex compilation to get a bit slower across the board. Basically, as long as regex compilation times remain "reasonable," then I consider that okay. Even if a regex compiles twice as slowly, if the absolute time is still "reasonable," then that is acceptable.

**Comment by BurntSushi** [comment] 2023-05-03 18:23
@marmeladema Do you have any more details you can share here? I am particularly interested whether these are "just" some observations of some metrics, or if they are having a meaningful impact on overall system performance.

**Comment by marmeladema** [comment] 2023-05-03 18:26
Sorry, I am a bit swamped with work at the moment. I'll try to find some time next week to provide more details.
We have temporarily decided to hold on from updating the regex crate until further analysis has been completed so I'll need to do it sooner than later.
Very sorry for the delay 😬

**Comment by BurntSushi** [comment] 2023-05-04 11:54
Aye. And y'all have see the `CHANGELOG` entry for `regex 1.8` right? `regex 1.9` is going to be a complete rewrite of the regex crate. So there are definitely going to be some changes there as well. I plan to release that within the next month. And I do expect compile times to get worse in some cases in `regex 1.9`. Search times are also more likely to change. Hopefully, in general, for the better. In some cases, much better. But there will undoubtedly be some cases where search times get slower.

Popping up a level, it would overall be good to get a better sense what y'all's perspective is here. Like, if I see a benchmark for regex compile time add `10μs` across the board, then a regex that previously compiled in `10μs` would get twice as slow. But if I know that's because I added an optimization that leads to faster search times, I'm probably going to be totally fine with that. Because from my perspective, `10μs` during regex compilation time is unlikely to materially impact anyone. _But_, it would still lead to issues like "some regexes now compile twice as slow."

I think popping up a level here is important so that I can better understand your use cases and so that we can communicate with each other more effectively. :-)

**Comment by marmeladema** [comment] 2023-05-13 13:41
> Aye. And y'all have see the CHANGELOG entry for regex 1.8 right? regex 1.9 is going to be a complete rewrite of the regex crate. So there are definitely going to be some changes there as well. I plan to release that within the next month. And I do expect compile times to get worse in some cases in regex 1.9. Search times are also more likely to change. Hopefully, in general, for the better. In some cases, much better. But there will undoubtedly be some cases where search times get slower.

Yes, we are actually looking forward to it :)
I opened the issue because I wanted to confirm that the performance degradation we saw were "expected".

I managed to get some examples of patterns that substantially slower to compile with the new version.
Here is the sample code I used to measure this:
```Rust
let now = Instant::now();

for _ in 0..10000 {
    let _regex = black_box(regex::bytes::RegexBuilder::new(black_box(&pattern))
        .unicode(false)
        .build()
        .unwrap());
}

println!("took: {:?}", now.elapsed());
```

And here are some examples of problematic patterns:

* `![!+ ]\[\]`

regex 1.7.3
```
Pattern: ![!+ ]\[\]
took: 181.657291ms

 Performance counter stats for './target/release/regex-builder ![!+ ]\[\]':

            182.19 msec task-clock:u              #    0.998 CPUs utilized          
                 0      context-switches:u        #    0.000 K/sec                  
                 0      cpu-migrations:u          #    0.000 K/sec                  
               138      page-faults:u             #    0.757 K/sec                  
       818,627,695      cycles:u                  #    4.493 GHz                    
     2,613,383,362      instructions:u            #    3.19  insn per cycle         
       623,738,418      branches:u                # 3423.499 M/sec                  
         1,301,739      branch-misses:u           #    0.21% of all branches        

       0.182582348 seconds time elapsed

       0.181293000 seconds user
       0.000950000 seconds sys
```

regex 1.8.1
```
Pattern: ![!+ ]\[\]
took: 311.364745ms

 Performance counter stats for './target/release/regex-builder ![!+ ]\[\]':

            312.12 msec task-clock:u              #    0.998 CPUs utilized          
                 0      context-switches:u        #    0.000 K/sec                  
                 0      cpu-migrations:u          #    0.000 K/sec                  
               150      page-faults:u             #    0.481 K/sec                  
     1,428,922,626      cycles:u                  #    4.578 GHz                    
     4,895,160,421      instructions:u            #    3.43  insn per cycle         
       985,991,923      branches:u                # 3159.049 M/sec                  
         1,736,944      branch-misses:u           #    0.18% of all branches        

       0.312650148 seconds time elapsed

       0.312197000 seconds user
       0.000000000 seconds sys
```

time: `181.657291ms` vs `311.364745ms` => +71%
instructions: ` 2,613,383,362` vs `4,895,160,421` => +87%

* `(?i:(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||like|and|div|&&)\s+\s*?\w+\(|\)\s*?when\s*?\d+\s*?then|[`]\s*?(?:--|\{|#)|cha?r\s*?\(\s*?\d|/\*!\s?\d+))`

regex 1.7.3
```
Pattern: (?i:(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||like|and|div|&&)\s+\s*?\w+\(|\)\s*?when\s*?\d+\s*?then|[`]\s*?(?:--|\{|#)|cha?r\s*?\(\s*?\d|/\*!\s?\d+))
took: 1.868526026s

 Performance counter stats for './target/release/regex-builder (?i:(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||like|and|div|&&)\s+\s*?\w+\(|\)\s*?when\s*?\d+\s*?then|[`]\s*?(?:--|\{|#)|cha?r\s*?\(\s*?\d|/\*!\s?\d+))':

          1,869.23 msec task-clock:u              #    1.000 CPUs utilized          
                 0      context-switches:u        #    0.000 K/sec                  
                 0      cpu-migrations:u          #    0.000 K/sec                  
               217      page-faults:u             #    0.116 K/sec                  
     8,276,173,879      cycles:u                  #    4.428 GHz                    
    23,190,818,740      instructions:u            #    2.80  insn per cycle         
     4,968,708,953      branches:u                # 2658.156 M/sec                  
        67,703,076      branch-misses:u           #    1.36% of all branches        

       1.869815394 seconds time elapsed

       1.866415000 seconds user
       0.000999000 seconds sys
```

regex 1.8.1
```
Pattern: (?i:(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||like|and|div|&&)\s+\s*?\w+\(|\)\s*?when\s*?\d+\s*?then|[`]\s*?(?:--|\{|#)|cha?r\s*?\(\s*?\d|/\*!\s?\d+))
took: 4.691591999s

 Performance counter stats for './target/release/regex-builder (?i:(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||like|and|div|&&)\s+\s*?\w+\(|\)\s*?when\s*?\d+\s*?then|[`]\s*?(?:--|\{|#)|cha?r\s*?\(\s*?\d|/\*!\s?\d+))':

          4,691.85 msec task-clock:u              #    1.000 CPUs utilized          
                 0      context-switches:u        #    0.000 K/sec                  
                 0      cpu-migrations:u          #    0.000 K/sec                  
            85,998      page-faults:u             #    0.018 M/sec                  
    19,939,742,954      cycles:u                  #    4.250 GHz                    
    53,575,748,989      instructions:u            #    2.69  insn per cycle         
    10,978,343,701      branches:u                # 2339.877 M/sec                  
       181,337,551      branch-misses:u           #    1.65% of all branches        

       4.693186680 seconds time elapsed

       4.495784000 seconds user
       0.180343000 seconds sys
```

time: `1.868526026s` vs `4.691591999s` => +151%
instructions: ` 2,613,383,362` vs `4,895,160,421` => +131%

I should be able to find more examples if needed but I figured starting with those two might be a good start.
Those are not made up pathological patterns, they were found in a corpus of production patterns extracted from [OWASP ModSecurity Core Rule Set](https://owasp.org/www-project-modsecurity-core-rule-set/).

> Popping up a level, it would overall be good to get a better sense what y'all's perspective is here. Like, if I see a benchmark for regex compile time add 10μs across the board, then a regex that previously compiled in 10μs would get twice as slow. But if I know that's because I added an optimization that leads to faster search times, I'm probably going to be totally fine with that. Because from my perspective, 10μs during regex compilation time is unlikely to materially impact anyone. But, it would still lead to issues like "some regexes now compile twice as slow."

We re likely to be on the same page on this :) But for version 1.8.1 we did not notice substantial matching performance improvement, only performance degradation of building / compiling regexes.

**Comment by BurntSushi** [comment] 2023-05-14 13:26
OK, so for the second pattern, it looks like #978 makes things a bit better, although still slower than `1.7.3`:

```
$ ./target/release/old '(?i:(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||like|and|div|&&)\s+\s*?\w+\(|\)\s*?when\s*?\d+\s*?then|[`]\s*?(?:--|\{|#)|cha?r\s*?\(\s*?\d|/\*!\s?\d+))'
took: 1.412362917s
$ ./target/release/new '(?i:(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||like|and|div|&&)\s+\s*?\w+\(|\)\s*?when\s*?\d+\s*?then|[`]\s*?(?:--|\{|#)|cha?r\s*?\(\s*?\d|/\*!\s?\d+))'
took: 3.326621837s
$ ./target/release/new2 '(?i:(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||like|and|div|&&)\s+\s*?\w+\(|\)\s*?when\s*?\d+\s*?then|[`]\s*?(?:--|\{|#)|cha?r\s*?\(\s*?\d|/\*!\s?\d+))'
took: 2.237951835s
```

Where `new2` corresponds to #978. So what's going on here? Looking at a profile leads me to some educated guesses:

* Lots of stuff in the new literal extractor are lighting up. The new literal extractor is part of 1.8. It's worth saying that in 1.7, the old literal extractor lights up as well. But, at a glance, not as much. This makes sense to me because the new literal extractor does a bit more work to try and find a better set of literals to search with. The thinking behind this is that it should lead to faster searches.
* `new2` also uses the new literal extractor but is much faster than `new`, which uses the new literal extractor with the old regex engines. Why? One guess is that in the status quo (so that's `old` and `new`), three different Thompson NFAs are compiled, where as in `new2` only two Thompson NFAs are compiled. I had hoped this would end up improving compile times for regexes, but the rewrite does a fair bit of extra work at compile time.

The literal extractor is clearly working at least a little hard for this pattern, as it has lots of interesting prefixes. Here's a selection of the log output for building a new regex in #978 that might hint at what's going on here:

```
[2023-05-14T12:51:48Z DEBUG regex_automata::meta::regex] building meta regex with 1 patterns:
[2023-05-14T12:51:48Z DEBUG regex_automata::meta::regex] PatternID(0): (?i:(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||like|and|div|&&)\s+\s*?\w+\(|\)\s*?when\s*?\d+\s*?then|[`]\s*?(?:--|\{
|#)|cha?r\s*?\(\s*?\d|/\*!\s?\d+))
[2023-05-14T12:51:48Z DEBUG regex_automata::util::prefilter] prefixes (len=Some(213), exact=false) extracted before optimization: Seq[I("NAND"), I("NANd"), I("NAnD"), I("NAnd"), I("NaND")
, I("NaNd"), I("NanD"), I("Nand"), I("NOT"), I("NOt"), I("NoT"), I("Not"), I("nAND"), I("nANd"), I("nAnD"), I("nAnd"), I("naND"), I("naNd"), I("nanD"), I("nand"), I("nOT"), I("nOt"), I("n
oT"), I("not"), I("XXOR"), I("XXOr"), I("XXoR"), I("XXor"), I("XxOR"), I("XxOr"), I("XxoR"), I("Xxor"), I("xXOR"), I("xXOr"), I("xXoR"), I("xXor"), I("xxOR"), I("xxOr"), I("xxoR"), I("xxo
r"), I("XOR"), I("XOr"), I("XoR"), I("Xor"), I("xOR"), I("xOr"), I("xoR"), I("xor"), I("OR"), I("Or"), I("oR"), I("or"), I("BETW"), I("BETw"), I("BEtW"), I("BEtw"), I("BeTW"), I("BeTw"),
I("BetW"), I("Betw"), I("bETW"), I("bETw"), I("bEtW"), I("bEtw"), I("beTW"), I("beTw"), I("betW"), I("betw"), I("||"), I("LIKE"), I("LIKe"), I("LIkE"), I("LIke"), I("LiKE"), I("LiKe"), I(
"LikE"), I("Like"), I("lIKE"), I("lIKe"), I("lIkE"), I("lIke"), I("liKE"), I("liKe"), I("likE"), I("like"), I("AND"), I("ANd"), I("AnD"), I("And"), I("aND"), I("aNd"), I("anD"), I("and"),
 I("DIV"), I("DIv"), I("DiV"), I("Div"), I("dIV"), I("dIv"), I("diV"), I("div"), I("&&"), I(")WHE"), I(")WHe"), I(")WhE"), I(")Whe"), I(")wHE"), I(")wHe"), I(")whE"), I(")whe"), I(")\t"),
 I(")\n"), I(")\x0b"), I(")\x0c"), I(")\r"), I(") "), E("`--"), E("`{"), E("`#"), I("`\t"), I("`\n"), I("`\x0b"), I("`\x0c"), I("`\r"), I("` "), I("CHAR"), I("CHAr"), I("CHaR"), I("CHar")
, I("CHR("), I("CHR\t"), I("CHR\n"), I("CHR\x0b"), I("CHR\x0c"), I("CHR\r"), I("CHR "), I("CHr("), I("CHr\t"), I("CHr\n"), I("CHr\x0b"), I("CHr\x0c"), I("CHr\r"), I("CHr "), I("ChAR"), I(
"ChAr"), I("ChaR"), I("Char"), I("ChR("), I("ChR\t"), I("ChR\n"), I("ChR\x0b"), I("ChR\x0c"), I("ChR\r"), I("ChR "), I("Chr("), I("Chr\t"), I("Chr\n"), I("Chr\x0b"), I("Chr\x0c"), I("Chr\
r"), I("Chr "), I("cHAR"), I("cHAr"), I("cHaR"), I("cHar"), I("cHR("), I("cHR\t"), I("cHR\n"), I("cHR\x0b"), I("cHR\x0c"), I("cHR\r"), I("cHR "), I("cHr("), I("cHr\t"), I("cHr\n"), I("cHr
\x0b"), I("cHr\x0c"), I("cHr\r"), I("cHr "), I("chAR"), I("chAr"), I("chaR"), I("char"), I("chR("), I("chR\t"), I("chR\n"), I("chR\x0b"), I("chR\x0c"), I("chR\r"), I("chR "), I("chr("), I
("chr\t"), I("chr\n"), I("chr\x0b"), I("chr\x0c"), I("chr\r"), I("chr "), I("/*!\t"), I("/*!\n"), I("/*!\x0b"), I("/*!\x0c"), I("/*!\r"), I("/*! "), I("/*!0"), I("/*!1"), I("/*!2"), I("/*
!3"), I("/*!4"), I("/*!5"), I("/*!6"), I("/*!7"), I("/*!8"), I("/*!9")]
[2023-05-14T12:51:48Z DEBUG regex_automata::util::prefilter] prefixes (len=Some(21), exact=false) extracted after optimization: Seq[I("N"), I("n"), I("X"), I("x"), I("O"), I("o"), I("B"),
 I("b"), I("|"), I("L"), I("l"), I("A"), I("a"), I("D"), I("d"), I("&"), I(")"), I("`"), I("C"), I("c"), I("/")]
[2023-05-14T12:51:48Z DEBUG regex_automata::meta::strategy] creating prefilter from 21 literals: [I("N"), I("n"), I("X"), I("x"), I("O"), I("o"), I("B"), I("b"), I("|"), I("L"), I("l"), I
("A"), I("a"), I("D"), I("d"), I("&"), I(")"), I("`"), I("C"), I("c"), I("/")]
[2023-05-14T12:51:48Z DEBUG aho_corasick::packed::api] trying to build Teddy packed matcher
[2023-05-14T12:51:48Z DEBUG aho_corasick::packed::teddy::compile] Teddy choice: 256-bit slim, 1 byte
[2023-05-14T12:51:48Z DEBUG aho_corasick::nfa::noncontiguous] building non-contiguous NFA
[2023-05-14T12:51:48Z DEBUG aho_corasick::nfa::noncontiguous] non-contiguous NFA built, <states: 25, size: 7628>
[2023-05-14T12:51:48Z DEBUG aho_corasick::dfa] building DFA
[2023-05-14T12:51:48Z DEBUG aho_corasick::dfa] DFA built, <states: 25, size: 7072, alphabet len: 34, stride: 64>
[2023-05-14T12:51:48Z DEBUG regex_automata::util::prefilter] prefilter built: teddy
```

> We re likely to be on the same page on this :) But for version 1.8.1 we did not notice substantial matching performance improvement, only performance degradation of building / compiling regexes.

Yeah I mean this is pretty tricky. A lot of the "optimizations" in a regex engine involve doing more work at compile time that _may_ result in faster search times. A lot of the optimizations are heuristics, especially when it comes to literal extraction. It's a dangerous game to play because it's very likely that the new literal extractor will make some searches faster while making other searches a little slower.

I also looked at the first pattern with the rewrite too:

```
$ ./target/release/old '![!+ ]\[\]'
took: 140.840081ms
$ ./target/release/new '![!+ ]\[\]'
took: 235.966597ms
$ ./target/release/new2 '![!+ ]\[\]'
took: 59.341359ms
```

So in this case, things get a lot faster in the rewrite. But it's mostly just dumb luck I think? In this case, `old` and `new` fed the literals to an Aho-Corasick builder, where as `new2` notices that it would probably be faster to just run `memchr` on `!` (a common prefix). So `new2` just doesn't build an Aho-Corasick automaton at all.

But why is `new` slower than `old`? Well, I think I would attribute that to the fact that `new` uses `aho-corasick 1.0` where as `old` uses `aho-corasick 0.7`. At least, it looks like building an Aho-Corasick automaton takes up more time in `new` than it does in `old`. But we're talking about 3 patterns here corresponding to expanding the pattern out into literals. So we are in turn probably talking about constant factors here. I wouldn't be surprised that those increased in `aho-corasick 1.0`. 

-----

Soon after regex 1.9 is published, I plan to publish a mammoth suite of regex benchmarks. Once that happens, I would very much welcome contributions from you folks that adds as many regex benchmarks as you want. It won't guarantee that those benchmarks will never regress, but it I think it will make them much more visible as targets to optimize for.

That benchmark suite is my main evidence for saying that the rewrite is faster. But for search times:

```
$ rebar rank record/all/2023-05-04/*.csv -e '^(rust/regex|rust/regexold)$' -M compile
Engine         Version  Geometric mean of speed ratios  Benchmark count
------         -------  ------------------------------  ---------------
rust/regex     1.8.1    1.09                            242
rust/regexold  1.7.3    2.59                            234
```

But for compile times, it is a bit slower:

```
$ rebar rank record/all/2023-05-04/*.csv -e '^(rust/regex|rust/regexold)$' -m compile
Engine         Version  Geometric mean of speed ratios  Benchmark count
------         -------  ------------------------------  ---------------
rust/regexold  1.7.3    1.09                            25
rust/regex     1.8.1    1.40                            27
```

Where the ranking here is based on looking at the timings of all benchmarks for the new and old regex engine, computing the speed up ratio for each (where the fastest is `1.0`) and taking the geometric mean of all those ratios. So in the above, if an engine has a geometric mean of `1.0`, that means it is always faster than the other. But even for search times, the rewrite is not always faster, as demonstrated by the fact that its geometric mean is greater than `1.0`. That implies the old regex crate beats it in some cases.

The question is, what are "some cases"? The benchmark suite tries to draw in a diversity of patterns, but what if all of the patterns y'all use fall into the bucket of the "some cases" where the old regex crate is faster? That's tricky business.

Overall, I would say that this is somewhat expected? To be honest, these sorts of questions are really really really hard to answer. Are these regressions fixable? Not sure. They are definitely not high on my priority list. It's almost certainly the case that compile times can be improved, but there is a fundamental tension here between spending more time doing heuristic optimizations at compile time and not. As an example of that, I have an in-progress crate called `regex-lite` that tries to match the semantics and API of the `regex` crate, but without Unicode support. The goal is for faster crate compile times and smaller binary sizes and simpler code. As a result, compiling a regex in that crate is super duper fast:

```
$ rebar rank record/all/2023-05-04/*.csv -e '^(rust/regex|rust/regexold|rust/regex/lite)$' -m compile
Engine           Version  Geometric mean of speed ratios  Benchmark count
------           -------  ------------------------------  ---------------
rust/regex/lite  0.1.0    1.00                            10
rust/regexold    1.7.3    2.32                            25
rust/regex       1.8.1    2.82                            27
```

So that `1.0` means its faster in _all_ cases. That perfectly exhibits the tension here. It also explains why your question can't really be answered in a satisfactory manner.

**Comment by BurntSushi** [comment] 2023-05-19 18:35
I took a closer look at `(?i:(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||like|and|div|&&)\s+\s*?\w+\(|\)\s*?when\s*?\d+\s*?then|[`]\s*?(?:--|\{|#)|cha?r\s*?\(\s*?\d|/\*!\s?\d+))`. It seems like this is just a particularly gnarly case for literal extraction. I took four different measurements: one with regex 1.7.3, one in soon-to-be regex 1.9 and one in soon-to-be regex 1.9 but with all literal extraction disabled, and one final one for RE2:

```
regex 1.7                129.75us
regex 1.9                185.32us
regex 1.9 (no literals)   38.97us
re2                       25.82us
```

So basically, for this particular pattern, literal extraction seems to really slow things down. This is the first time I've really taken a close look at the performance of literal extraction, and I'm somewhat surprised that it takes more time than NFA compilation. I think this particular pattern just has a bunch of literals in it, and it takes time to traverse and cull the literal sets. regex 1.9 (and also regex 1.8) in particular introduce a new "preference trie" that tries to minimize the literal sequences based on leftmost-first match semantics. (For example, if you have `sam` and `samwise` in the same set of literals and `sam` appears before `samwise`, then `samwise` can be removed from the set without changing match semantics.)

One possible upshot of literal extraction is that it doesn't (hopefully?) get much worse than this. Namely, once "too many" literals have been extracted, it gives up. This particular pattern I think just happens to get close to that limit.

I did take a brief look at optimizing literal extraction, but I don't see any obvious wins. The biggest time sink is the preference trie minimization, which isn't present at all in regex 1.7.

One downside of this is that the extra time spent in literal extraction doesn't necessarily result in faster search times. It merely represents a gambit that it *might* result in faster search times.

**Comment by marmeladema** [comment] 2023-05-23 13:11
Thank you for your detailed analysis!

I also ran our benchmarks against future 1.9 at https://github.com/rust-lang/regex/commit/a68aa532ef3dd52ff107973866e6372293b851da

And it effectively mitigates *some* of the compilation regressions, but definitely not all of them.
However that version comes with *substantial* execution performance gains (between 5% to 10%), which after some analysis, we believe balances the regressions so we will actually wait for 1.9 to be out and skip 1.8 completely.

**Comment by BurntSushi** [comment] 2023-05-23 13:14
Sounds good. That's great to hear about the search time wins!

**Comment by marmeladema** [comment] 2023-05-23 13:15
> Soon after regex 1.9 is published, I plan to publish a mammoth suite of regex benchmarks. Once that happens, I would very much welcome contributions from you folks that adds as many regex benchmarks as you want. It won't guarantee that those benchmarks will never regress, but it I think it will make them much more visible as targets to optimize for.

We can definitely help here. I believe we can curate a good set of nasty patterns that we are running in production but are publicly shareable.

**Comment by BurntSushi** [comment] 2023-05-23 13:17
That's perfect. I would love to have those!

**Comment by BurntSushi** [comment] 2023-05-25 11:33
All right I think I'm going to close this issue. It sounds like 1.9 should help with some of these and y'all have a plan on your end.

Once 1.9 is released, if there are any new problems we can look at them in a new issue.

**Closed** 2023-05-25 11:33 UTC
Labels: question
