### ISSUE TITLE
Replacement by patterns is broken in 0.2

### ISSUE THREAD

**Issue by e-oz** [rust-lang/regex#336] opened 2017-02-03 17:35 UTC
In 0.1.8 this code

```rust
    let regex = Regex::new("[:^word:]*").unwrap();
    let mut filtered = regex.replace_all("pa_date", "");
```
gives "pa_date" in `filtered`, in 0.2 it gives "pa_ate".
Also,

```
  let regex = Regex::new("[:^digit:]*").unwrap();
  let stripped = regex.replace_all(phone.as_str(), "");
```
just removes some digits in 0.2.
Some phone numbers are forever lost because of this cruel awful bug.

**Comment by BurntSushi** [comment] 2017-02-03 17:41
This sounds like a dupe of #314 which was fixed a while ago. Are you using `0.2.0` or `0.2.1`? If you're using `0.2.0`, then you should upgrade to `0.2.1`.

**Comment by e-oz** [comment] 2017-02-03 17:43
No, it was freshest version (0.2.1, I checked git history), installed just yesterday. had to rollback to 0.1.8 today.

**Comment by BurntSushi** [comment] 2017-02-03 18:01
Oh, I see. This is a breaking change documented in the [`CHANGELOG`](https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#020):

> POSIX character classes now require double bracketing. Previously, the regex [:upper:] would parse as the upper POSIX character class. Now it parses as the character class containing the characters :upper:. The fix to this change is to use [[:upper:]] instead. Note that variants like [[:upper:][:blank:]] continue to work.

**Closed by BurntSushi** 2017-02-03 18:01 UTC

**Comment by e-oz** [comment] 2017-02-03 18:03
thank you! sorry for being to careless to changelog
