### ISSUE TITLE
remember matched group name and index in regex

### ISSUE THREAD

**Issue by qdwang** [rust-lang/regex#59] opened 2015-03-19 16:33 UTC
```rust
let re = Regex::new(r"([a-zA-Z_][a-zA-Z0-9]*)|([0-9]+)|(\.)|(=)").unwrap();

for cap in re.captures_iter("asdf.aeg = 34") {
    let mut index = 0;
    for (i, name) in cap.iter().enumerate() {
        if i == 0 {continue}
        if let Some(_) = name {index = i; break;}
    }
    println!("group {:?}, match {:?}", index, cap.at(index).unwrap());
}
```
Now, we can only use ```iter``` to get the matched group index or name. But it will cost O(n) time at the worst case.

Pls add the feature to remember the matched group name and index, then only O(1) time will be consumed.

**Comment by BurntSushi** [comment] 2015-03-19 17:03
Can you please describe the problem you're trying to solve?

**Comment by qdwang** [comment] 2015-03-20 02:33
Using
```rust
let re = Regex::new(r"([a-zA-Z_][a-zA-Z0-9]*)|([0-9]+)|(\.)|(=)").unwrap();
```
When matching ```"asdf.aeg = 34"``` get
```
group index 1, match "asdf"
group index 3, match "."
group index 1, match "aeg"
group index 4, match "="
group index 2, match "34"
```
Just want to get the each group index in O(1) time. No need to take a iter to find the index.

**Comment by BurntSushi** [comment] 2015-03-20 11:05
It sounds like what you want is the index of the *first capture group that matches* in `O(1)` time. In the example you've given, the `O(n)` solution seems perfectly fine to me because `n` is tiny. I suspect that this is true for most real world use cases too.

In order to add this feature (and comply strictly with the `O(1)` requirement), the regex VM would have to actually keep track of the first capture group that matches. This seems like a lot of work for probably zero gain (other than a nicer theoretical property).

I'm not inclined to get on board with this, but I'm happy to leave the issue open for now in case there is a real world use case that would materially benefit from a change like this.

**Comment by BurntSushi** [comment] 2015-06-19 19:24
I'm going to close this because I'm not convinced this is actually worth adding. If there's a more compelling use case that I'm missing, I'm happy to try and work through it with you. (A benchmark would be handy too, since O(n) where n is typically tiny probably isn't a big deal.)

**Closed by BurntSushi** 2015-06-19 19:24 UTC

**Comment by jnordwick** [comment] 2015-07-07 06:24
Horrible decision. "N" might be small for you, but these decisions lead to a generally poor set of libraries. Try telling somebody writing an NLP tokenizer over a large corpus or a compiler writer or somebody parsing news feeds for stock trading this. I really think you should reconsider. Rust is made to be performance based, and it seems strange to make such concessions in critcal library code.

**Comment by huonw** [comment] 2015-07-07 06:39
Hey, @jnordwick, do you happen to have a benchmark you can feed @BurntSushi? He's very responsive to feedback, and the decision seems totally reasonable given [the context](https://github.com/rust-lang/regex/issues/59#issuecomment-113613553), since presumably this feature may cause complications internally. :smile:

(I'm sure everyone will be super-receptive if we don't get stuck in an unnecessarily aggressive discussion.)

**Comment by jnordwick** [comment] 2015-07-07 08:11
@huonw I've found a few acceptable ways around it, especially if it would cause a lot of grief in the code. Part of it was my misunderstanding of the str slice and part of it is going with a few simplier string matchers. I have to write KMP and Rabin-Karp rolling hash anyways.

**Comment by BurntSushi** [comment] 2015-07-07 11:16
@jnordwick Yes, please try to be friendly and constructive.

Could you help me make a better decision by providing some data? A benchmark would be great!

I'm also not aware of other regex libraries that provide this information. Have you used one? If so, I'd love to take a peek.

> I have to write KMP and Rabin-Karp rolling hash anyways.

If you're in this domain of problems, then you may find [aho-corasick](https://github.com/BurntSushi/aho-corasick) useful. I built it for use inside this crate, so its API isn't as useful as it could be. But I'd be happy to iterate on it with you.

**Comment by JonWaterfall** [comment] 2024-10-30 23:34
Hi. I'm in the process of learning Rust, and I ended up on [this StackOverflow post](https://stackoverflow.com/questions/29126533/how-to-get-the-index-of-matching-group-in-the-regex-crate/29140265) after having scratched my head against a problem.
I'm sad that this never became a feature for captures_iter. Because Match has this feature with the [Start](https://docs.rs/regex/latest/regex/struct.Match.html#method.start) and End methods.

So if I have a file that might have hundreds of matches where I need the index for something, I'd then have to re-slice the string for each match, or implement my own linear search function.

[.NET has this feature](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.matches?view=netframework-1.1)

**Comment by BurntSushi** [comment] 2024-10-30 23:47
@JonWaterfall Please provide an MRE. I have honestly no earthly clue what you're talking about. Everything on that .NET page is supported by this crate as far as I can tell, and there is literally nothing that a Match gives you that you can't very easily get from Captures.

**Comment by JonWaterfall** [comment] 2024-10-31 00:06
@BurntSushi Thank you for swift response. I am still in the process of learning so I apologize for the roughness of my previous post.

I don't have a proper Minimal reproducible example(is that what the abbreviation is?) on hand right now but I can write one up tomorrow after some bed rest(it's currently 1 am where I am).

What I feel is missing from Captures, or that I can't identify has a method for; is to get the byte offset of the start of the match from the given haystack

**Comment by BurntSushi** [comment] 2024-10-31 00:19
> What I feel is missing from Captures, or that I can't identify has a method for; is to get the byte offset of the start of the match from the given haystack

That's `caps.get(0).unwrap()`. This is very different from what this issue is about.

Questions like this are very welcome. But start with the question and not the assumption that there is no solution. :) And please ask it as a new Discussion question. Include MREs whenever possible (you got the abbreviation correct).
