### ISSUE TITLE
how to make rust regex compatible with online regex or other languages regex?

### ISSUE THREAD

**Issue by shachardevops** [rust-lang/regex#727] opened 2020-11-29 10:36 UTC
I have plenty of regexes and I can't change them
```
regex parse error:
    .*Stop pulling image "([a-z0-9\.\-\:\/]+)": "Status: Image is up to date for [a-z0-9\.\-\:\/]+"
                                      ^^
error: unrecognized escape sequence
```
for example.
ad many more... there is a way to overcome this issue?

**Comment by BurntSushi** [comment] 2020-11-29 12:38
Duplicate of https://github.com/rust-lang/regex/issues/501

Otherwise, you'll have to change the regex somehow.

**Closed by BurntSushi** 2020-11-29 12:38 UTC
