### ISSUE TITLE
chrono-tz doesn't build anymore with latest regex-syntax

### ISSUE THREAD

**Issue by meh** [rust-lang/regex#455] opened 2018-03-12 12:26 UTC
Sorry for finding these issues in small steps instead of all at once, one of the regular expressions in `chrono-tz` is not parsing anymore, which makes the build script fail.

The regular expression comes from [here](https://github.com/chronotope/parse-zoneinfo/blob/master/src/line.rs#L68), an issue about it was opened [here](https://github.com/chronotope/chrono-tz/issues/18).

Would this be considered a breaking change since it was working before?

**Comment by BurntSushi** [comment] 2018-03-12 12:29
Yes, it's a bug, and not surprising sadly :-(. I was somewhat expecting bugs in the case insensitive mode. I wrote as many tests as I could think of, but it looks like some cases have eluded me! I will try to get a fix out today.

**Comment by BurntSushi** [comment] 2018-03-12 12:38
OK, I've reproduced this down to a minimal example:

```
(?x)[ / - ]
```

which produces

```
regex parse error:
    (?x)[ / - ]
        ^^
error: unclosed character class
```

Another variant:

```
(?x)[ a - ]
```

which produces

```
regex parse error:
    (?x)[ a - ]
          ^^^^^
error: invalid character class range, the start must be <= the end
```

In other words, the parser is treating the trailing `-` as if it signified a range, but it should actually treat the regexes as equivalent to `[/-]` (or `[a-]`), which is a special case of character class syntax where the trailing `-` is treated as a literal `-` instead of a marker for a range. We get `[/-]` right, but not `(?x)[ / - ]` right, presumably because the check for the trailing `-` is not accounting for whitespace insensitive mode.

This should be straight-forward to fix.

**Comment by meh** [comment] 2018-03-12 12:43
Nice, I'm going to add `[patch.crates-io]` for `regex-syntax` when it's fixed so I can see if there's anything else that affects me before I make you go through the release churn again :panda_face:

**Comment by BurntSushi** [comment] 2018-03-12 12:43
Thanks! <3 :)

**Comment by BurntSushi** [comment] 2018-03-12 13:27
OK, I've pushed a fix. I did try running your `chrono-tz` tests and everything seemed to work. If you have other crates with lots of regexes, it would be much appreciated to test those too if possible! :-)

**Closed** 2018-03-12 13:27 UTC

**Comment by meh** [comment] 2018-03-12 13:38
Everything is building and all tests are green here.

**Comment by BurntSushi** [comment] 2018-03-12 13:50
@meh `regex-syntax 0.5.2` is now on crates.io with this fix. I don't believe a new `regex` release is required. (Come to think of it, the previous release of `regex` wasn't required either, although I did that to bring in the `nest_limit` API.)

**Comment by meh** [comment] 2018-03-12 17:43
Everything seems to be still fine, so thanks a bunch :panda_face:
