### ISSUE TITLE
`regex-syntax` fails to compile with `unicode-perl` feature

### ISSUE THREAD

**Issue by ThouCheese** [rust-lang/regex#770] opened 2021-05-01 22:31 UTC
#### What version of regex are you using?

Regex `1.5.2`, regex-syntax `0.6.24`

#### Describe the bug at a high level.

`regex-syntax` doesn't compile when default features are turned off and `unicode-perl` is turned on.

#### What are the steps to reproduce the behavior?

Create a new cargo project and list either `regex` or `regex-syntax` with default-features turned off and `unicode-perl` turned on. Easy repro: clone this git repository: https://github.com/ThouCheese/regex-issue

#### What is the actual behavior?

I expect this to compile.

#### What is the expected behavior?

I doesn't compile with the error message:

```
    |
375 |         use unicode_tables::perl_decimal::DECIMAL_NUMBER;
    |             ^^^^^^^^^^^^^^ use of undeclared crate or module `unicode_tables`
```

This should be fixed if line 375 is changed to `use crate::unicode_tables::perl_decimal::DECIMAL_NUMBER;`, I believe.

**Comment by BurntSushi** [comment] 2021-05-01 22:34
Dupe of #769.

Thanks for reporting this though!

**Comment by BurntSushi** [comment] 2021-05-01 22:35
#771 is a PR in progress to fix this and fix CI so that these regressions actually failed the build.

**Closed by BurntSushi** 2021-05-01 22:34 UTC

**Comment by ThouCheese** [comment] 2021-05-01 22:36
Too slow! Thanks for the quick reply Andrew!
