### ISSUE TITLE
replace has problems with empty strings

### ISSUE THREAD

**Issue by fulara** [rust-lang/regex#394] opened 2017-08-20 14:47 UTC
Seems like a replace has problems processing empty strings. example:
```
extern crate regex;
use regex::Regex;
fn main() {
    let regex = Regex::new("\\d*").unwrap();
    let s = regex.replace("", "replaced").into_owned();
    assert_eq!("replaced", s);
}
```
That fails. however:
```
extern crate regex;
use regex::Regex;
fn main() {
    let regex = Regex::new("\\d*").unwrap();
    let s = regex.find("");
    assert!(s.is_some());
}
```
That one passes.
Thanks to lapinot I've workaround here:
```
extern crate regex;
use regex::Regex;
fn main() {
    let regex = Regex::new("\\d*").unwrap();
    let s = regex.replace("", |caps: &regex::Captures| { "replaced".to_string() }).into_owned();
    assert_eq!("replaced", s);
}
```

**Comment by BurntSushi** [comment] 2017-08-20 14:49
This is probably a dupe of #393, but we can leave this open until a fix confirms.

**Comment by BurntSushi** [comment] 2017-12-03 13:42
Fixed by #395

**Closed by BurntSushi** 2017-12-03 13:42 UTC
Labels: bug
