### ISSUE TITLE
please support \" and \' as equivalent to " and ' respectively

### ISSUE THREAD

**Issue by zackw** [rust-lang/regex#522] opened 2018-10-08 12:41 UTC
It would enhance compatibility with other regex engines if `regex` understood `\"` and `\'` as equivalents of `"` and `'`.

This came up for me when trying to use Rust's regexes from Python (Python's built-in regex module doesn't have an equivalent of RegexSet).  Python's raw string literals _do_ recognize some backslash escapes for purpose of deciding where the literal ends, so for instance `r"<a href=\"https?://([a-z0-9.-]+)/robots.txt\">"` is a single string literal — but they _don't_ convert those escapes, so the contents of the parsed string are the same as if you had written `"<a href=\\\"https?://([a-z0-9.-]+)/robots.txt\\\">"`.  Python's built-in regex module understands this to mean the same thing as if the quote characters were not escaped., but `regex` will barf on the `\"`.

This could also come up in any other context where backslash escapes quote characters but is not removed from the input in the process.  For instance, some parsers for Windows-style .cfg files do this.

**Comment by RReverser** [comment] 2018-10-08 13:06
I'd say current behaviour is probably better, as what you're describing is not necessarily expected fallback behaviour by everyone... for example, in another case I had regexes with escapes that were supposed to be treated as normal escaped chars (`\"` should be treated as `"` and so on). So it's likely better to explicitly barf rather than just assume what user wants.

**Comment by RReverser** [comment] 2018-10-08 13:07
(nvm my previous comment, sounds like you want the same)

**Comment by BurntSushi** [comment] 2018-10-08 13:10
I think this is a dupe of #501 (I've just renamed that issue to have a better title). I've also left a comment in that issue responding to your request in an effort to centralize discussion: https://github.com/rust-lang/regex/issues/501#issuecomment-427826260

**Closed by BurntSushi** 2018-10-08 13:10 UTC
