### ISSUE TITLE
Use the same name of a capture group in different alternatives of disjunction (| operator)

### ISSUE THREAD

**Issue by fedy-cz** [rust-lang/regex#1128] opened 2023-11-16 17:14 UTC
It looks like the regex crate requires that all of the named capture groups have a unique name. Maybe it could allow use of the same name in different branches of the disjuction operator (`|`).

For example the javascript regex engine [allows this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Named_capturing_group) (quote):
> All names must be unique within the same pattern. Multiple named capturing groups with the same name result in a syntax error.
> This restriction is relaxed if the duplicate named capturing groups are not in the same [disjunction alternative](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Disjunction), so for any string input, only one named capturing group can actually be matched. This is a much newer feature, so check [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Named_capturing_group#browser_compatibility) before using it.
>
> ```
> /(?<year>\d{4})-\d{2}|\d{2}-(?<year>\d{4})/;
> // Works; "year" can either come before or after the hyphen
> ```
Could make some "simple parsers" a little bit nicer.

**Comment by BurntSushi** [comment] 2023-11-16 17:24
Duplicate of #492.

Note that [`regex-automata` lets you search for multiple regexes with duplicative capture names](https://docs.rs/regex-automata/latest/regex_automata/index.html#multi-pattern-searches-with-capture-groups). That likely achieves the effect you want here, but you'll need to drop down to `regex-automata` which exists at a bit of a lower level of abstraction. The easiest path will be to use the [meta regex engine](https://docs.rs/regex-automata/latest/regex_automata/meta/struct.Regex.html).

**Closed by BurntSushi** 2023-11-16 17:24 UTC
