### ISSUE TITLE
[Feature Request] API for non-contiguous data structures

### ISSUE THREAD

**Issue by ngortheone** [rust-lang/regex#580] opened 2019-05-13 20:33 UTC
Using regexes with data structures like ropes, gap-buffers, string arrays etc requres allocating data to contiguous memory area (String, &str) before regex can be executed 

These allocations can be quite costly, especially if search is unbounded, executed repeatedly, or if regular expression is multiline - it requires copying the whole contents of the data structure to a String, which completely undermines the very purpose of using such data structure.

Please implement some kind of Cursor API that would allow regex engine to use non-contiguous data structures and avoid allocations.

Relevant problem in xi-rope:
https://github.com/xi-editor/xi-editor/issues/1192

**Comment by BurntSushi** [comment] 2019-05-13 21:09
Duplicate of #425

> Please implement some kind of Cursor API that would allow regex engine to use non-contiguous data structures and avoid allocations.

This isn't a simple matter of "just implement an API." It carries _significant_ implementation complexity, and as #425 discusses, there are some potential performance pitfalls.

See also [`regex-automata` which exposes a low level DFA API](https://docs.rs/regex-automata/0.1.6/regex_automata/trait.DFA.html) and [streaming search in `aho-corasick`](https://docs.rs/aho-corasick/0.7.3/aho_corasick/struct.AhoCorasick.html#method.stream_find_iter).

One thing the xi project could do to help things would be to come up with an API (expressed in Rust code) that would be suitable for your use case. That should go in #425.

**Closed by BurntSushi** 2019-05-13 21:09 UTC
