### ISSUE TITLE
Space in Verbose Mode

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/regex#385] opened 2017-06-28 09:55 UTC
In Python you can use `[ ]` to indicate a space if verbose mode is enabled:

```python
>>> re.compile('(?x)a b c [ ] d').match('abc d').group()
'abc d'
```

This is really neat and convenient. Currently if you do that in Rust's regex it gives a syntax error because the empty range is not valid. Any thoughts about supporting this?

**Comment by BurntSushi** [comment] 2017-06-28 11:04
Seems like a duplicate of #383? Happy to hear other arguments...

**Comment by mitsuhiko** [comment] 2017-06-28 11:54
So my argument is that the regular expression engines i'm familiar with that have verbose mode treat `[ ]` as space and not as syntax error (Ruby, Perl, PHP, Python). Additionally obviously `[]` is a syntax error so it's not ambiguous since nobody would write such a thing.

**Comment by BurntSushi** [comment] 2017-06-28 12:02
What are the semantics of `[ a]` in verbose mode? Are they different from `[ ]` in verbose mode? Why is `\\ ` insufficient? Note that `\\ ` seems to work in Python as well.

**Comment by mitsuhiko** [comment] 2017-06-28 12:31
> What are the semantics of [ a] in verbose mode?

Generally within `[]` a space means a space. So `[a ]` matches both a and a space.

> Why is \\ insufficient?

To be quite honest: I have never escaped spaces in verbose regexes. I stumbled across this because I loaded verbose regexes that are used in python and ruby and was surprised to see that they were syntax errors in this library. I suppose this is something you could do a poll on to see what people expect.

**Comment by mitsuhiko** [comment] 2017-06-28 12:34
One thing I should add is that backslash escaped space is often not ideal because the whitespace you match on often appears at the end of the line. What I was matching on is this:

```
(?x)
^
                (?P<filename>[^:]+):
                (?P<line>\d+):
                (?P<column>\d+):[ ]
                (?P<code>\S+)[ ]
                (?P<message>.*)
              $
```

**Comment by BurntSushi** [comment] 2017-12-03 13:53
I think this feature request boils down to one of two paths forward:

1. Make it so verbose mode does not apply inside character classes.
2. Special case `[ ]` so that even in verbose mode, it is treated as a space character.

In addition to (1) being a breaking change, it is also a change that I do not agree with. It seems quite useful to be able to insert line breaks and comments inside a character class.

(2) is something I could possibly get on board with (and is not a breaking change, since it is currently an error), but I'd really rather not have weird special cases like that.

With respect to your last regex, you could today write it like this:

```
(?x)
^
  (?P<filename>[^:]+):
  (?P<line>\d+):
  (?P<column>\d+):[\ ]
  (?P<code>\S+)[\ ]
  (?P<message>.*)
$
```

**Closed by BurntSushi** 2017-12-03 13:53 UTC

**Comment by vbrozik** [comment] 2022-04-05 09:28
@BurntSushi
I have come to this issue by chance by Google search but I would like to add my opinion.

1. Character classes were treated as verbatim as possible in the orignal BRE so logically it makes sense that in verbose regex the character classes are not verbose.
2. Please do not invent yet another regex variant. Try to be as close as possible to the most prevailing regex variants. Probably best would be to select a single variant as a reference and implement it completely or subset of it.

I do not know much about regex variants but the need to cope with them is very tiresome.

**Comment by BurntSushi** [comment] 2022-04-05 09:38
@vbrozik If you have specific actionable feedback, please open a new issue. If you have a question, feel free to put it in Discussions. Otherwise your comment doesn't seem appropriate for this issue, which is closed.

Consider that third library is and has been at 1.0 for several years now. The time for whether to implement an existing regex standard (which?) or not has long passed.
