### ISSUE TITLE
Version 1.5.0 should be yanked

### ISSUE THREAD

**Issue by carloskiki** [rust-lang/regex#1220] opened 2024-08-08 01:26 UTC
#### Describe the bug at a high level.

`criterion` depends on `regex = "1.5"`. If you have a dependency on criterion, or any crate that depends on `regex = "1.5"`, building with `-Zminimal-versions` fails because `regex` does not build on version 1.5.0 (with some feature flag enabled). Therefore, this version should be yanked in order to make builds depending on `regex = "1.5"` succeed.

See [CHANGELOG.md version 1.5.1](https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#151-2021-04-30).

#### What are the steps to reproduce the behavior?
With any crate having `regex = "1.5"`:
1.
```bash
cargo +nightly update -Zminimal-versions
```

2.
```bash
cargo build
```

**Comment by BurntSushi** [comment] 2024-08-08 01:29
I think the resolution here is to increase the minimal version. I don't like to yank unless there's a very compelling reason to do so.

**Comment by BurntSushi** [comment] 2024-08-08 01:30
Duplicate of #931.

**Closed by BurntSushi** 2024-08-08 01:30 UTC
